### ISSUE TITLE
ssh after launch prompts for password

### ISSUE THREAD

**Issue by richardasaurus** [yoshz/ansible-digitalocean#3]
After using `launch.yml` to create a fresh droplet. When I attempt to ssh into that droplet I'm prompted for password input, despite the key not having one.

any idea why?

```bash
>> ssh user@domain
>> user@domain's password:
```

**Comment by yoshz** [comment]
Solved it yourself?

**Comment by richardasaurus** [comment]
Yes my dns was pointing at an old destroyed box (idiot),
