### ISSUE TITLE
Auto generation of ssh key

### ISSUE THREAD

**Issue by kbariotis** [yoshz/ansible-digitalocean#4]
Do you think it would be a good idea to automatically generate an ssh key to the local machine and adding it to DO. Given that anyone that uses a project like this, she's going to keep it secret so from whatever machine she's trying to use it, she will have access as long as she has the DO token.

What do you think?

**Comment by yoshz** [comment]
In my opinion it should be up to the user to decide if it wants a new ssh key or use an existing one.
It is a good practice to add it as an installation step for projects like this.

**Comment by kbariotis** [comment]
Should I make a PR to add a prompt whether the user wants to use the default or create a new one? The new one will have the droplet's name.

**Comment by yoshz** [comment]
I am not sure if it should be part of this project, as it is something what you do on your local machine and not on the remote server, but I am curious to see how you will set it up.
